baseURL = 'https://kentcasandra-portfolio.vercel.app/'
languageCode = 'en-us'
title = 'Kent Casandra'
theme = "PaperMod"

[outputs]
    home = ["HTML", "RSS"]

[params]
    env = "production"
    [params.homeInfoParams]
        Title = "Hi there! I'm Kent."
        Content = "SoftDev OJT at Callbox"
    [params.profileMode]
        enabled = true
        title = "Kent Casandra"
        subtitle = "Automation Specialist"