baseURL = 'https://kentcasandra-portfolio.vercel.app/'
languageCode = 'en-us'
title = 'Kent Casandra'
theme = "PaperMod"

# Add this block to force HTML generation
[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    env = "production"
    # This enables the "landing page" style
    [params.homeInfoParams]
        Title = "Hi there! I'm Kent. 👋"
        Content = "SoftDev OJT at Callbox | Automation Specialist"

    # This makes the layout focus on your profile
    [params.profileMode]
        enabled = true
        title = "Kent Casandra"
        subtitle = "Software Development Trainee"